DELETE FROM `script_texts` WHERE `entry` BETWEEN '-1000433' AND '-1000416';
INSERT INTO `script_texts` VALUES ('-1000433', '%s fades away after a long pause.', null, null, null, null, null, null, null, null, '0', '2', '0', '0', 'ringo EMOTE_RIN_END_8');
INSERT INTO `script_texts` VALUES ('-1000432', 'Ringo? Wake up! Don\'t worry, I\'ll take care of you.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'ringo SAY_SPR_END_7');
INSERT INTO `script_texts` VALUES ('-1000431', 'Ugh.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'ringo SAY_RIN_END_6');
INSERT INTO `script_texts` VALUES ('-1000430', '%s stands up after a short pause.', null, null, null, null, null, null, null, null, '0', '2', '0', '0', 'ringo EMOTE_RIN_END_5');
INSERT INTO `script_texts` VALUES ('-1000429', '%s collapses onto the ground.', null, null, null, null, null, null, null, null, '0', '2', '0', '0', 'ringo EMOTE_RIN_END_4');
INSERT INTO `script_texts` VALUES ('-1000428', 'Oh... I\'m feeling faint...', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'ringo SAY_RIN_END_3');
INSERT INTO `script_texts` VALUES ('-1000427', 'Ringo! You\'re okay!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'ringo SAY_SPR_END_2');
INSERT INTO `script_texts` VALUES ('-1000425', 'How am I feeling? Quite soaked, thank you.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'ringo SAY_WAKE_4');
INSERT INTO `script_texts` VALUES ('-1000426', 'Spraggle! I didn\'t think I\'d make it back!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'ringo SAY_RIN_END_1');
INSERT INTO `script_texts` VALUES ('-1000423', 'I am feeling a little better now, thank you.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'ringo SAY_WAKE_2');
INSERT INTO `script_texts` VALUES ('-1000424', 'Yes, I must go on.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'ringo SAY_WAKE_3');
INSERT INTO `script_texts` VALUES ('-1000421', 'I\'m not feeling so well...', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'ringo SAY_FAINT_4');
INSERT INTO `script_texts` VALUES ('-1000422', 'Where... Where am I?', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'ringo SAY_WAKE_1');
INSERT INTO `script_texts` VALUES ('-1000419', 'Maybe... you could carry me?', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'ringo SAY_FAINT_2');
INSERT INTO `script_texts` VALUES ('-1000420', 'Uuuuuuggggghhhhh....', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'ringo SAY_FAINT_3');
INSERT INTO `script_texts` VALUES ('-1000418', 'The heat... I can\'t take it...', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'ringo SAY_FAINT_1');
INSERT INTO `script_texts` VALUES ('-1000417', 'Remember, if I faint again, the water that Spraggle gave you will revive me.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'ringo SAY_RIN_START_2');
INSERT INTO `script_texts` VALUES ('-1000416', 'Well, I\'m not sure how far I\'ll make it in this state... I\'m feeling kind of faint...', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'ringo SAY_RIN_START_1');
UPDATE `creature_template` SET `ScriptName` = 'npc_ringo' WHERE `entry` = '9999';
UPDATE `quest_template` SET `SpecialFlags` = '2' WHERE `entry` = '4491';