UPDATE `creature_template` SET `ScriptName` = 'npc_prospector_remtravel' WHERE `entry` = '2917';
UPDATE `creature_template` SET `ScriptName` = 'npc_threshwackonator' WHERE `entry` = '6669';
UPDATE `creature_template` SET `ScriptName` = 'npc_kerlonian' WHERE `entry` = '11218';
UPDATE `quest_template` SET `SpecialFlags` = '2' WHERE `entry` = '731';
UPDATE `quest_template` SET `SpecialFlags` = '2' WHERE `entry` = '5321';
DELETE FROM `script_texts` WHERE `entry` BETWEEN '-1600444' AND '-1600413';
INSERT INTO `script_texts` VALUES ('-1600444', 'Oh, I can see Liladris from here... Tell her I\'m here, won\'t you?', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'kerlonian SAY_KER_END');
INSERT INTO `script_texts` VALUES ('-1600440', 'Oh, I am so tired...', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'kerlonian SAY_KER_SLEEP_3');
INSERT INTO `script_texts` VALUES ('-1600441', 'You don\'t mind if I stop here for a moment, do you?', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'kerlonian SAY_KER_SLEEP_4');
INSERT INTO `script_texts` VALUES ('-1600442', 'Be on the alert! The Blackwood furbolgs are numerous in the area...', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'kerlonian SAY_KER_ALERT_1');
INSERT INTO `script_texts` VALUES ('-1600443', 'It\'s quiet... Too quiet...', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'kerlonian SAY_KER_ALERT_2');
INSERT INTO `script_texts` VALUES ('-1600439', 'Yaaaaawwwwwnnnn...', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'kerlonian SAY_KER_SLEEP_2');
INSERT INTO `script_texts` VALUES ('-1600438', 'This looks like the perfect place for a nap...', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'kerlonian SAY_KER_SLEEP_1');
INSERT INTO `script_texts` VALUES ('-1600437', '%s begins to drift off...', null, null, null, null, null, null, null, null, '0', '2', '0', '0', 'kerlonian EMOTE_KER_SLEEP_3');
INSERT INTO `script_texts` VALUES ('-1600435', '%s looks very sleepy...', null, null, null, null, null, null, null, null, '0', '2', '0', '0', 'kerlonian EMOTE_KER_SLEEP_1');
INSERT INTO `script_texts` VALUES ('-1600436', '%s suddenly falls asleep', null, null, null, null, null, null, null, null, '0', '2', '0', '0', 'kerlonian EMOTE_KER_SLEEP_2');
INSERT INTO `script_texts` VALUES ('-1600434', 'Liladris has been waiting for me at Maestra\'s Post, so we should make haste, $N.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'kerlonian SAY_KER_START');
INSERT INTO `script_texts` VALUES ('-1600427', 'Something tells me this $r wants the mysterious fossil too. Help!', null, null, null, null, null, null, null, null, '0', '0', '7', '0', 'remtravel SAY_REM_AGGRO');
INSERT INTO `script_texts` VALUES ('-1600426', '%s goes back to work, oblivious to everything around him.', null, null, null, null, null, null, null, null, '0', '2', '7', '0', 'remtravel EMOTE_REM_END');
INSERT INTO `script_texts` VALUES ('-1600425', 'Ah. I remember now! I gave the mysterious fossil to Hollee! Check with her.', null, null, null, null, null, null, null, null, '0', '0', '7', '0', 'remtravel SAY_REM_REMEMBER');
INSERT INTO `script_texts` VALUES ('-1600424', 'Nope. didn\'t leave the fossil back here!', null, null, null, null, null, null, null, null, '0', '0', '7', '0', 'remtravel SAY_REM_PROGRESS');
INSERT INTO `script_texts` VALUES ('-1600423', 'Oh wait! I\'m supposed to be looking for that mysterious fossil!', null, null, null, null, null, null, null, null, '0', '0', '7', '0', 'remtravel SAY_REM_MOSS_PROGRESS');
INSERT INTO `script_texts` VALUES ('-1600422', '%s inspects the ancient, mossy stone.', null, null, null, null, null, null, null, null, '0', '2', '7', '0', 'remtravel EMOTE_REM_MOSS');
INSERT INTO `script_texts` VALUES ('-1600421', 'Interesting... I hadn\'t noticed this earlier...', null, null, null, null, null, null, null, null, '0', '0', '7', '0', 'remtravel SAY_REM_MOSS');
INSERT INTO `script_texts` VALUES ('-1600420', 'Oh wait, that\'s Hollee\'s tent... and it\'s empty.', null, null, null, null, null, null, null, null, '0', '0', '7', '0', 'remtravel SAY_REM_TENT1_2');
INSERT INTO `script_texts` VALUES ('-1600419', 'I bet you I left it in the tent!', null, null, null, null, null, null, null, null, '0', '0', '7', '0', 'remtravel SAY_REM_TENT1_1');
INSERT INTO `script_texts` VALUES ('-1600418', 'No mysterious fossil here... Ah, but my copy of Green Hills of Stranglethorn. What a good book!', null, null, null, null, null, null, null, null, '0', '0', '7', '0', 'remtravel SAY_REM_BOOK');
INSERT INTO `script_texts` VALUES ('-1600417', 'Hrm, nothing up here.', null, null, null, null, null, null, null, null, '0', '0', '7', '0', 'remtravel SAY_REM_RAMP1_2');
INSERT INTO `script_texts` VALUES ('-1600416', 'Now where did I put that mysterious fossil? Ah, maybe up there...', null, null, null, null, null, null, null, null, '0', '0', '7', '0', 'remtravel SAY_REM_RAMP1_1');
INSERT INTO `script_texts` VALUES ('-1600415', 'Ok, $n, let\'s go find where I left that mysterious fossil. Follow me!', null, null, null, null, null, null, null, null, '0', '0', '7', '0', 'remtravel SAY_REM_START');
INSERT INTO `script_texts` VALUES ('-1600414', 'YARRR! Swabie, what have ye done?! He\'s gone mad! Baton him down the hatches! Hoist the mast! ARRRR! Every man for hi\'self!', null, null, null, null, null, null, null, null, '0', '0', '7', '0', 'threshwackonator SAY_AT_CLOSE');
INSERT INTO `script_texts` VALUES ('-1600413', '\"Threshwackonator First Mate unit prepared to follow\"', null, null, null, null, null, null, null, null, '0', '2', '0', '0', 'threshwackonator EMOTE_START');