UPDATE `creature_template` SET `ScriptName` = 'npc_private_hendel' WHERE `entry` = '4966';
UPDATE `quest_template` SET `SpecialFlags` = '2' WHERE `entry` = '1324';
DELETE FROM `script_texts` WHERE `entry` BETWEEN '-1600415' AND '-1600411';
INSERT INTO `script_texts` VALUES ('-1600411', 'Why don\'t we deal with you now, Hendel? Lady Proudmoore will speak for you back in the tower.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'hendel SAY_PROGRESS_1_TER');
INSERT INTO `script_texts` VALUES ('-1600412', 'Please... please... Miss Proudmore. I didn\'t mean to...', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'hendel SAY_PROGRESS_2_HEN');
INSERT INTO `script_texts` VALUES ('-1600413', 'I apologize for taking so long to get here. I wanted Lady Proudmoore to be present also.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'hendel SAY_PROGRESS_3_TER');
INSERT INTO `script_texts` VALUES ('-1600414', 'We can only stay a few moments before returning to the tower. If you wish to speak to us more you may find us there.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'hendel SAY_PROGRESS_4_TER');
INSERT INTO `script_texts` VALUES ('-1600415', 'Private Hendel, too injured, gives up the chase.', null, null, null, null, null, null, null, null, '0', '2', '0', '0', 'hendel EMOTE_SURRENDER');
UPDATE `creature_template` SET `ScriptName` = 'npc_ogron' WHERE `entry` = '4983';
UPDATE `quest_template` SET `SpecialFlags` = '2' WHERE `entry` = '1273';
DELETE FROM `script_texts` WHERE `entry` BETWEEN '-1800471' AND '-1800452';
INSERT INTO `script_texts` VALUES ('-1800452', 'I noticed some fire on that island over there. A human, too. Let\'s go check it out, $N.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'SAY_OGR_START');
INSERT INTO `script_texts` VALUES ('-1800453', 'That\'s Reethe alright. Let\'s go see what he has to say, yeah?', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'SAY_OGR_SPOT');
INSERT INTO `script_texts` VALUES ('-1800454', 'W-what do you want? Just leave me alone...', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'SAY_OGR_RET_WHAT');
INSERT INTO `script_texts` VALUES ('-1800455', 'I swear. I didn\'t steal anything from you! Here, take some of my supplies, just go away!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'SAY_OGR_RET_SWEAR');
INSERT INTO `script_texts` VALUES ('-1800456', 'Just tell us what you know about the Shady Rest Inn, and I won\'t bash your skull in.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'SAY_OGR_REPLY_RET');
INSERT INTO `script_texts` VALUES ('-1800457', 'I... Well, I may of taken a little thing or two from the inn... but what would an ogre care about that?', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'SAY_OGR_RET_TAKEN');
INSERT INTO `script_texts` VALUES ('-1800458', 'Look here, if you don\'t tell me about the fire...', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'SAY_OGR_TELL_FIRE');
INSERT INTO `script_texts` VALUES ('-1800459', 'Not one step closer, ogre!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'SAY_OGR_RET_NOCLOSER');
INSERT INTO `script_texts` VALUES ('-1800460', 'And I don\'t know anything about this fire of yours...', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'SAY_OGR_RET_NOFIRE');
INSERT INTO `script_texts` VALUES ('-1800461', 'What was that? Did you hear something?', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'SAY_OGR_RET_HEAR');
INSERT INTO `script_texts` VALUES ('-1800462', 'Paval Reethe! Found you at last. And consorting with ogres now? No fear, even deserters and traitors are afforded some mercy.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'SAY_OGR_CAL_FOUND');
INSERT INTO `script_texts` VALUES ('-1800463', 'Private, show Lieutenant Reethe some mercy.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'SAY_OGR_CAL_MERCY');
INSERT INTO `script_texts` VALUES ('-1800464', 'Gladly, sir.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'SAY_OGR_HALL_GLAD');
INSERT INTO `script_texts` VALUES ('-1800465', '%s staggers backwards as the arrow lodges itself deeply in his chest.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'EMOTE_OGR_RET_ARROW');
INSERT INTO `script_texts` VALUES ('-1800466', 'Ugh... Hallan, didn\'t think you had it in you...', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'SAY_OGR_RET_ARROW');
INSERT INTO `script_texts` VALUES ('-1800467', 'Now, let\'s clean up the rest of the trash, men!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'SAY_OGR_CAL_CLEANUP');
INSERT INTO `script_texts` VALUES ('-1800468', 'Damn it! You\'d better not die on me, human!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'SAY_OGR_NODIE');
INSERT INTO `script_texts` VALUES ('-1800469', 'Still with us, Reethe?', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'SAY_OGR_SURVIVE');
INSERT INTO `script_texts` VALUES ('-1800470', 'Must be your lucky day. Alright, I\'ll talk. Just leave me alone. Look, you\'re not going to believe me, but it wa... oh, Light, looks like the girl could shoot...', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'SAY_OGR_RET_LUCKY');
INSERT INTO `script_texts` VALUES ('-1800471', 'By the way, thanks for watching my back.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'SAY_OGR_THANKS');
UPDATE `creature_template` SET `ScriptName` = 'npc_morokk' WHERE `entry` = '4500';
UPDATE `quest_template` SET `SpecialFlags` = '2' WHERE `entry` = '1173';
UPDATE `quest_template` SET `ReqCreatureOrGOId1` = '0' WHERE `entry` = '1173';
UPDATE `quest_template` SET `ReqCreatureOrGOCount1` = '0' WHERE `entry` = '1173';
DELETE FROM `script_texts` WHERE `entry` BETWEEN '-1600500' AND '-1600499';
INSERT INTO `script_texts` VALUES ('-1600499', 'Puny $r wanna fight with Overlord Mok\'Morokk? Me beat you! Me boss here!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', 'morokk SAY_MOR_CHALLENGE');
INSERT INTO `script_texts` VALUES ('-1600500', 'Me scared! Me run now!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', 'morokk SAY_MOR_SCARED');
